---
title: "FoodJustice"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    social: menu
    source_code: embed
runtime: shiny
---

```{r global, include=FALSE}
# load data in 'global' chunk so it can be shared by all users of the dashboard
library(ggplot2)
library(mgcv)
library(shiny)
library(flexdashboard)
library(tidyverse)
library(here)
dataset <- read_csv(here("data/chr_pressures_by_food_type.csv"))
options(scipen = 99)


```

```{r}
dataset <- dataset %>% 
  select(sum_cumulative_pressure, per_low_birthweight, per_freq_mental_distress, per_freq_mental_distress, life_expectancy)

dataset <- dataset %>% 
  drop_na()
```



Inputs {.sidebar}
-----------------------------------------------------------------------

```{r}
# numericInput('sum_cumulative_pressure', 'Cumulative Pressure of Food Production', value = 0.001, min = 0.0000005438458, max = 0.02727833, step = 0.0006)
# 
# numericInput('per_low_birthweight', 'Percentage of Low Birthweights', value = 8, min = 3, max = 22, step = 1)







#
sliderInput('sampleSize', 'Sample Size', min=3000, max=3000,
            value=3000, step=0, round=0)

checkboxInput('jitter', 'Jitter', value = TRUE)
checkboxInput('smooth', 'Smooth', value = FALSE)

selectInput('x', 'X', names(dataset))
selectInput('y', 'Y', names(dataset), names(dataset)[[2]])
selectInput('color', 'Color', c('None', names(dataset)))

selectInput('facet_row', 'Facet Row',
            c(None='.', names(dataset)))
selectInput('facet_col', 'Facet Column',
            c(None='.', names(dataset)))
```


Outputs
-----------------------------------------------------------------------

### Data

```{r}
# dataset <- reactive({
#   dataset[sample(nrow(dataset), input$sampleSize),]
# })

renderPlot({
  p <- ggplot(data = dataset, aes_string(x=input$x, y=input$y)) + geom_point()
  
  if (input$color != 'None')
    p <- p + aes_string(color=input$color)
  
  facets <- paste(input$facet_row, '~', input$facet_col)
  if (facets != '. ~ .')
    p <- p + facet_grid(facets)
  
  if (input$jitter)
    p <- p + geom_jitter()
  if (input$smooth)
    p <- p + geom_smooth()
  
  print(p)
})
```
